# -*- coding: utf-8 -*-
"""collect_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KQNO2bkG0hdmHTBXKc83p6ZKDxvGHU4
"""

"""
collect_data.py
===============
ETL Step 1: Copy raw TMDB CSV files into a single staging CSV.

Source files (place in the working directory before running):
    tmdb_5000_movies.csv
    tmdb_5000_credits.csv

Output:
    raw_tmdb_data.csv   – merged movies + credits on movie_id
"""

import pandas as pd
from sqlalchemy import create_engine, text

# ── Config ────────────────────────────────────────────────────────────────────

MOVIES_FILE  = "tmdb_5000_movies.csv"
CREDITS_FILE = "tmdb_5000_credits.csv"
OUTPUT_FILE  = "raw_tmdb_data.csv"

DB_HOST = "your_host"
DB_PORT = 3306
DB_NAME = "tmdb_moviess"
DB_USER = "root"
DB_PASS = "bread12345678"


def get_existing_movie_ids() -> set:
    """
    Return the set of movie_ids already loaded in the DB.
    Falls back to empty set if DB is unreachable (triggers full load).
    """
    try:
        engine = create_engine(
            f"mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}",
            echo=False,
        )
        with engine.connect() as conn:
            rows = conn.execute(text("SELECT movie_id FROM movies")).fetchall()
        ids = {r[0] for r in rows}
        print(f"  DB has {len(ids)} existing movies -> incremental mode")
        return ids
    except Exception as exc:
        print(f"  DB unreachable ({exc}), falling back to full load")
        return set()

def load_movies(existing_ids: set) -> pd.DataFrame:
    """
    Read tmdb_5000_movies.csv, drop movies already in DB,
    and return a clean DataFrame.
    """
    print(f"  Reading {MOVIES_FILE}...")
    df = pd.read_csv(MOVIES_FILE)

    # Rename 'id' to 'movie_id' to match the credits file and DB schema
    df = df.rename(columns={"id": "movie_id"})

    if existing_ids:
        before = len(df)
        df = df[~df["movie_id"].isin(existing_ids)]
        print(f"    Skipping {before - len(df)} already-loaded movies; {len(df)} new")
    else:
        print(f"    {len(df)} movies to load (full load)")

    return df


def load_credits(movie_ids: pd.Index) -> pd.DataFrame:
    """
    Read tmdb_5000_credits.csv and keep only rows whose movie_id
    appears in the new movies batch.
    """
    print(f"  Reading {CREDITS_FILE}...")
    df = pd.read_csv(CREDITS_FILE)
    df = df[df["movie_id"].isin(movie_ids)][["movie_id", "cast", "crew"]]
    print(f"    {len(df)} credit rows matched")
    return df


movies_df  = load_movies(get_existing_movie_ids())
credits_df = load_credits(movies_df["movie_id"])
movies_df.head(3)

def collect_data() -> None:
    """Run full Step 1: load CSVs, merge, save to staging file."""
    print(f"=== collect_data | output: {OUTPUT_FILE} ===\n")

    existing_ids = get_existing_movie_ids()
    movies_df    = load_movies(existing_ids)

    if movies_df.empty:
        print("Nothing new to load. Exiting.")
        return

    credits_df = load_credits(movies_df["movie_id"])

    # Left join so movies with missing credits are still kept
    merged = movies_df.merge(credits_df, on="movie_id", how="left")

    merged.to_csv(OUTPUT_FILE, index=False)
    print(f"\nSaved -> {OUTPUT_FILE}")
    print(f"  Rows:    {len(merged)}")
    print(f"  Columns: {merged.shape[1]}")
    print(f"  Column list: {list(merged.columns)}")


collect_data()