# -*- coding: utf-8 -*-
"""load_to_mysql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKpEcvkvvw1oqvZZxJShLhtnn7WB1NPc
"""

"""
load_to_mysql.py
================
ETL Step 3: Read prepared CSVs and load into MySQL.

Load order is fixed by FK dependencies:
  1. genres, keywords, production_companies  (reference tables, no FK)
  2. movies                                  (references nothing)
  3. movie_genres, movie_keywords,           (FK -> movies + ref tables)
     movie_companies
  4. cast, crew                              (FK -> movies)

DDL (run once in MySQL before this script):
---------------------------------------------
CREATE TABLE genres (
    genre_id   INT PRIMARY KEY,
    genre_name VARCHAR(100) NOT NULL
);

CREATE TABLE keywords (
    keyword_id   INT PRIMARY KEY,
    keyword_name VARCHAR(200) NOT NULL
);

CREATE TABLE production_companies (
    company_id   INT PRIMARY KEY,
    company_name VARCHAR(300) NOT NULL
);

CREATE TABLE movies (
    movie_id          INT PRIMARY KEY,
    title             VARCHAR(300),
    original_title    VARCHAR(300),
    original_language CHAR(10),
    overview          TEXT,
    tagline           TEXT,
    status            VARCHAR(50),
    homepage          TEXT,
    budget            BIGINT,
    revenue           BIGINT,
    runtime           INT,
    popularity        FLOAT,
    vote_average      FLOAT,
    vote_count        INT,
    vote_weighted     FLOAT,
    release_date      DATE,
    release_year      SMALLINT,
    release_month     TINYINT,
    profit            BIGINT,
    roi               FLOAT
);

CREATE TABLE movie_genres (
    movie_id INT, genre_id INT,
    PRIMARY KEY (movie_id, genre_id),
    FOREIGN KEY (movie_id)  REFERENCES movies(movie_id),
    FOREIGN KEY (genre_id)  REFERENCES genres(genre_id)
);

CREATE TABLE movie_keywords (
    movie_id INT, keyword_id INT,
    PRIMARY KEY (movie_id, keyword_id),
    FOREIGN KEY (movie_id)   REFERENCES movies(movie_id),
    FOREIGN KEY (keyword_id) REFERENCES keywords(keyword_id)
);

CREATE TABLE movie_companies (
    movie_id INT, company_id INT,
    PRIMARY KEY (movie_id, company_id),
    FOREIGN KEY (movie_id)   REFERENCES movies(movie_id),
    FOREIGN KEY (company_id) REFERENCES production_companies(company_id)
);

CREATE TABLE cast_members (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    movie_id   INT,
    person_id  INT,
    name       VARCHAR(300),
    character  TEXT,
    cast_order TINYINT,
    gender     TINYINT,
    UNIQUE KEY uq_movie_person (movie_id, person_id),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
);

CREATE TABLE crew_members (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    movie_id   INT,
    person_id  INT,
    name       VARCHAR(300),
    department VARCHAR(100),
    job        VARCHAR(200),
    gender     TINYINT,
    UNIQUE KEY uq_movie_person_job (movie_id, person_id, job),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
);
"""

import pandas as pd
from sqlalchemy import create_engine, text

# ── Config ────────────────────────────────────────────────────────────────────

DB_HOST = "127.0.0.1"
DB_PORT = 3306
DB_NAME = "tmdb_moviess"
DB_USER = "root"
DB_PASS = "bread12345678"

ENGINE = create_engine(
    f"mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}",
    echo=False
)

def test_connection():
    try:
        with ENGINE.connect() as conn:
            row = conn.execute(text("SELECT VERSION(), DATABASE(), NOW()")).fetchone()
            print(f"Connected: MySQL {row[0]} | db={row[1]} | server_time={row[2]}")

            tables = conn.execute(text("""
                SELECT TABLE_NAME, TABLE_ROWS
                FROM information_schema.TABLES
                WHERE TABLE_SCHEMA = :db
                ORDER BY TABLE_NAME
            """), {"db": DB_NAME}).fetchall()

            if tables:
                print(f"\nTables in '{DB_NAME}':")
                for t in tables:
                    print(f"  {t[0]:30s} (~{t[1] or 0} rows)")
            else:
                print(f"No tables in '{DB_NAME}' — run DDL first.")

    except Exception as e:
        print(f"Connection failed: {e}")
        raise SystemExit(1)

test_connection()

# ── Generic helpers ───────────────────────────────────────────────────────────

def _count(conn, table: str) -> int:
    return conn.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar()


def _existing_ids(conn, table: str, id_col: str) -> set:
    """Return the set of IDs already present in a table."""
    rows = conn.execute(text(f"SELECT {id_col} FROM {table}")).fetchall()
    return {r[0] for r in rows}


def _upsert_reference(conn, df: pd.DataFrame, table: str, id_col: str) -> None:
    """
    Insert reference-table rows that are not already in the DB.
    Uses INSERT IGNORE to skip duplicates gracefully.
    """
    existing = _existing_ids(conn, table, id_col)
    new_rows = df[~df[id_col].isin(existing)]
    if new_rows.empty:
        print(f"    {table}: nothing new")
        return
    new_rows.to_sql(table, conn, if_exists="append", index=False, method="multi", chunksize=500)
    print(f"    {table}: +{len(new_rows)} rows -> {_count(conn, table)} total")

# ── Loaders ───────────────────────────────────────────────────────────────────

def load_reference_tables(conn) -> None:
    """Load genres, keywords, production_companies (no FK dependencies)."""
    print("  Loading reference tables...")
    _upsert_reference(conn, pd.read_csv("table_genres.csv"),               "genres",                "genre_id")
    _upsert_reference(conn, pd.read_csv("table_keywords.csv"),             "keywords",              "keyword_id")
    _upsert_reference(conn, pd.read_csv("table_production_companies.csv"), "production_companies",  "company_id")


def load_movies(conn) -> None:
    """Insert new movies; skip any movie_id already in the DB."""
    print("  Loading movies...")
    df = pd.read_csv("table_movies.csv", parse_dates=["release_date"])

    existing = _existing_ids(conn, "movies", "movie_id")
    new_rows = df[~df["movie_id"].isin(existing)]

    if new_rows.empty:
        print(f"    movies: nothing new")
        return

    new_rows.to_sql("movies", conn, if_exists="append", index=False, method="multi", chunksize=500)
    print(f"    movies: +{len(new_rows)} rows -> {_count(conn, 'movies')} total")


def load_bridge(conn, csv_file: str, table: str, col1: str, col2: str) -> None:
    """
    Generic loader for many-to-many bridge tables.
    Skips rows whose (col1, col2) pair is already in the DB.
    """
    print(f"  Loading {table}...")
    df = pd.read_csv(csv_file)

    existing = set(
        conn.execute(text(f"SELECT {col1}, {col2} FROM {table}")).fetchall()
    )
    mask = df.apply(lambda r: (r[col1], r[col2]) not in existing, axis=1)
    new_rows = df[mask]

    if new_rows.empty:
        print(f"    {table}: nothing new")
        return

    new_rows.to_sql(table, conn, if_exists="append", index=False, method="multi", chunksize=1000)
    print(f"    {table}: +{len(new_rows)} rows -> {_count(conn, table)} total")


def load_cast(conn) -> None:
    """Insert cast rows for movies not yet in the DB."""
    print("  Loading cast_members...")
    df = pd.read_csv("table_cast.csv")

    loaded_movies = _existing_ids(conn, "cast_members", "movie_id")
    new_rows = df[~df["movie_id"].isin(loaded_movies)]

    if new_rows.empty:
        print("    cast_members: nothing new")
        return

    new_rows.to_sql("cast_members", conn, if_exists="append", index=False, method="multi", chunksize=1000)
    print(f"    cast_members: +{len(new_rows)} rows -> {_count(conn, 'cast_members')} total")


def load_crew(conn) -> None:
    """Insert crew rows for movies not yet in the DB."""
    print("  Loading crew_members...")
    df = pd.read_csv("table_crew.csv")

    loaded_movies = _existing_ids(conn, "crew_members", "movie_id")
    new_rows = df[~df["movie_id"].isin(loaded_movies)]

    if new_rows.empty:
        print("    crew_members: nothing new")
        return

    new_rows.to_sql("crew_members", conn, if_exists="append", index=False, method="multi", chunksize=1000)
    print(f"    crew_members: +{len(new_rows)} rows -> {_count(conn, 'crew_members')} total")

def load_to_mysql() -> None:
    """
    Run full Step 3.
    Load order respects FK constraints:
      reference tables -> movies -> bridges -> cast/crew
    """
    print(f"=== load_to_mysql | target: {DB_HOST}/{DB_NAME} ===\n")

    with ENGINE.begin() as conn:
        # 1. Reference tables (no FK)
        load_reference_tables(conn)
        print()

        # 2. Core movies table
        load_movies(conn)
        print()

        # 3. Bridge / junction tables (FK -> movies + ref tables)
        load_bridge(conn, "table_movie_genres.csv",   "movie_genres",   "movie_id", "genre_id")
        load_bridge(conn, "table_movie_keywords.csv", "movie_keywords", "movie_id", "keyword_id")
        load_bridge(conn, "table_movie_companies.csv","movie_companies","movie_id", "company_id")
        print()

        # 4. Cast & crew (FK -> movies)
        load_cast(conn)
        load_crew(conn)

    print("\nDone.")


load_to_mysql()