# -*- coding: utf-8 -*-
"""transform_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEpzTnB0xHyHugKe5vkzZ5pZ4T1o1_tW
"""

"""
transform_data.py
=================
ETL Step 2: Read raw_tmdb_data.csv, parse all JSON columns,
compute derived features, and split into relational tables.

Output CSVs (match MySQL schema exactly):
    table_movies.csv             – one row per movie (core facts + derived)
    table_genres.csv             – reference: unique genres
    table_movie_genres.csv       – bridge: movie <-> genre (many-to-many)
    table_keywords.csv           – reference: unique keywords
    table_movie_keywords.csv     – bridge: movie <-> keyword
    table_production_companies.csv – reference: unique companies
    table_movie_companies.csv    – bridge: movie <-> company
    table_cast.csv               – one row per actor per movie
    table_crew.csv               – one row per crew member per movie
"""

import json
import numpy as np
import pandas as pd

INPUT_FILE = "raw_tmdb_data.csv"


def load_raw() -> pd.DataFrame:
    df = pd.read_csv(INPUT_FILE)
    print(f"Loaded: {len(df)} rows, {df.shape[1]} columns")
    return df


def safe_json(val) -> list:
    """Parse a JSON string; return [] on any error."""
    try:
        return json.loads(val) if pd.notna(val) else []
    except Exception:
        return []


raw = load_raw()
raw.head(2)

# ── Core movies table ─────────────────────────────────────────────────────────

def build_movies(df: pd.DataFrame) -> pd.DataFrame:
    """
    Build the main movies table.

    Derived columns:
      profit          – revenue - budget  (null when either is 0 / unknown)
      roi             – profit / budget   (null when budget is 0)
      release_year    – year extracted from release_date
      release_month   – month extracted from release_date
      vote_weighted   – Bayesian-weighted rating, shrinks towards global mean
                        for movies with very few votes (m = 500 vote threshold)
    """
    m = df[[
        "movie_id", "title", "original_title", "original_language",
        "overview", "tagline", "status", "homepage",
        "budget", "revenue", "runtime",
        "popularity", "vote_average", "vote_count",
        "release_date",
    ]].copy()

    # Replace 0 with NaN for financial columns (0 means "unknown" in TMDB)
    m["budget"]  = m["budget"].replace(0, np.nan)
    m["revenue"] = m["revenue"].replace(0, np.nan)

    # Financial derived features
    m["profit"] = m["revenue"] - m["budget"]
    m["roi"]    = (m["profit"] / m["budget"]).replace([np.inf, -np.inf], np.nan)

    # Date features
    dates = pd.to_datetime(m["release_date"], errors="coerce")
    m["release_year"]  = dates.dt.year
    m["release_month"] = dates.dt.month

    # Bayesian-weighted vote score
    # Formula: (v / (v + m)) * R + (m / (v + m)) * C
    # where v = vote_count, m = 500 (minimum votes threshold),
    #       R = movie vote_average, C = global mean vote_average
    C = m["vote_average"].mean()
    min_votes = 500
    v = m["vote_count"]
    R = m["vote_average"]
    m["vote_weighted"] = ((v / (v + min_votes)) * R + (min_votes / (v + min_votes)) * C).round(4)

    m = m.sort_values("movie_id").reset_index(drop=True)
    print(f"  movies: {len(m):>6} rows")
    return m


movies = build_movies(raw)
movies.head(3)

# ── Genre reference + bridge ──────────────────────────────────────────────────

def build_genres(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Parse genres JSON -> deduplicated reference table + movie_genres bridge.
    """
    records = []
    for _, row in df[["movie_id", "genres"]].iterrows():
        for g in safe_json(row["genres"]):
            records.append({"genre_id": g["id"], "genre_name": g["name"], "movie_id": row["movie_id"]})

    all_genres = pd.DataFrame(records)

    genres_ref = (
        all_genres[["genre_id", "genre_name"]]
        .drop_duplicates("genre_id")
        .sort_values("genre_id")
        .reset_index(drop=True)
    )

    movie_genres = (
        all_genres[["movie_id", "genre_id"]]
        .drop_duplicates()
        .sort_values(["movie_id", "genre_id"])
        .reset_index(drop=True)
    )

    print(f"  genres:        {len(genres_ref):>6} unique genres")
    print(f"  movie_genres:  {len(movie_genres):>6} rows")
    return genres_ref, movie_genres


genres_ref, movie_genres = build_genres(raw)
genres_ref

# ── Keyword reference + bridge ────────────────────────────────────────────────

def build_keywords(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Parse keywords JSON -> deduplicated reference table + movie_keywords bridge.
    """
    records = []
    for _, row in df[["movie_id", "keywords"]].iterrows():
        for k in safe_json(row["keywords"]):
            records.append({"keyword_id": k["id"], "keyword_name": k["name"], "movie_id": row["movie_id"]})

    all_kw = pd.DataFrame(records)

    keywords_ref = (
        all_kw[["keyword_id", "keyword_name"]]
        .drop_duplicates("keyword_id")
        .sort_values("keyword_id")
        .reset_index(drop=True)
    )

    movie_keywords = (
        all_kw[["movie_id", "keyword_id"]]
        .drop_duplicates()
        .sort_values(["movie_id", "keyword_id"])
        .reset_index(drop=True)
    )

    print(f"  keywords:       {len(keywords_ref):>6} unique keywords")
    print(f"  movie_keywords: {len(movie_keywords):>6} rows")
    return keywords_ref, movie_keywords


keywords_ref, movie_keywords = build_keywords(raw)
keywords_ref.head(5)

# ── Production companies reference + bridge ───────────────────────────────────

def build_companies(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Parse production_companies JSON -> deduplicated reference table + bridge.
    """
    records = []
    for _, row in df[["movie_id", "production_companies"]].iterrows():
        for c in safe_json(row["production_companies"]):
            records.append({"company_id": c["id"], "company_name": c["name"], "movie_id": row["movie_id"]})

    all_co = pd.DataFrame(records)

    companies_ref = (
        all_co[["company_id", "company_name"]]
        .drop_duplicates("company_id")
        .sort_values("company_id")
        .reset_index(drop=True)
    )

    movie_companies = (
        all_co[["movie_id", "company_id"]]
        .drop_duplicates()
        .sort_values(["movie_id", "company_id"])
        .reset_index(drop=True)
    )

    print(f"  companies:       {len(companies_ref):>6} unique companies")
    print(f"  movie_companies: {len(movie_companies):>6} rows")
    return companies_ref, movie_companies


companies_ref, movie_companies = build_companies(raw)
companies_ref.head(5)

# ── Cast table ────────────────────────────────────────────────────────────────

def build_cast(df: pd.DataFrame) -> pd.DataFrame:
    """
    Explode the cast JSON array into one row per actor per movie.

    Columns:
      movie_id, person_id, name, characters, cast_order, gender

    cast_order=0 is the top-billed actor. Only the top 15 billed
    actors are kept to avoid huge tables for ensemble casts.
    """
    MAX_CAST = 15
    records = []
    for _, row in df[["movie_id", "cast"]].iterrows():
        for actor in safe_json(row["cast"]):
            if actor.get("order", 999) >= MAX_CAST:
                continue
            records.append({
                "movie_id":   row["movie_id"],
                "person_id":  actor["id"],
                "name":       actor["name"],
                "characters":  actor.get("character", ""),
                "cast_order": actor.get("order", None),
                "gender":     actor.get("gender", 0),  # 0=unknown,1=female,2=male
            })

    cast = (
        pd.DataFrame(records)
        .drop_duplicates(subset=["movie_id", "person_id"])
        .sort_values(["movie_id", "cast_order"])
        .reset_index(drop=True)
    )
    print(f"  cast: {len(cast):>7} rows (top {MAX_CAST} actors per movie)")
    return cast


cast = build_cast(raw)
cast.head(5)

# ── Crew table ────────────────────────────────────────────────────────────────

def build_crew(df: pd.DataFrame) -> pd.DataFrame:
    """
    Explode the crew JSON array into one row per crew member per movie.
    Only key departments are kept to focus on decision-makers:
      Directing, Writing, Production, and Visual Effects.

    Columns:
      movie_id, person_id, name, department, job, gender
    """
    KEY_DEPARTMENTS = {"Directing", "Writing", "Production", "Visual Effects"}

    records = []
    for _, row in df[["movie_id", "crew"]].iterrows():
        for member in safe_json(row["crew"]):
            dept = member.get("department", "")
            if dept not in KEY_DEPARTMENTS:
                continue
            records.append({
                "movie_id":   row["movie_id"],
                "person_id":  member["id"],
                "name":       member["name"],
                "department": dept,
                "job":        member.get("job", ""),
                "gender":     member.get("gender", 0),
            })

    crew = (
        pd.DataFrame(records)
        .drop_duplicates(subset=["movie_id", "person_id", "job"])
        .sort_values(["movie_id", "department", "job"])
        .reset_index(drop=True)
    )
    print(f"  crew: {len(crew):>7} rows (Directing/Writing/Production/VFX only)")
    return crew


crew = build_crew(raw)
crew.head(5)

def transform_data() -> None:
    """Run full Step 2: load -> parse -> derive -> split -> save."""
    print(f"=== transform_data | input: {INPUT_FILE} ===\n")

    raw = load_raw()

    print("\nBuilding tables:")
    movies_tbl                    = build_movies(raw)
    genres_ref, movie_genres      = build_genres(raw)
    keywords_ref, movie_keywords  = build_keywords(raw)
    companies_ref, movie_companies = build_companies(raw)
    cast_tbl                      = build_cast(raw)
    crew_tbl                      = build_crew(raw)

    outputs = {
        "table_movies.csv":               movies_tbl,
        "table_genres.csv":               genres_ref,
        "table_movie_genres.csv":         movie_genres,
        "table_keywords.csv":             keywords_ref,
        "table_movie_keywords.csv":       movie_keywords,
        "table_production_companies.csv": companies_ref,
        "table_movie_companies.csv":      movie_companies,
        "table_cast.csv":                 cast_tbl,
        "table_crew.csv":                 crew_tbl,
    }

    print("\nSaving:")
    for fname, frame in outputs.items():
        frame.to_csv(fname, index=False)
        print(f"  {fname}")

    print("\nDone. Next step: load_to_mysql.py")


transform_data()